### ISSUE TITLE
Error from server: error when creating "melonkube2.yaml": admission webhook "validator.experiment

### ISSUE THREAD

**Issue by yerim10044001** [seokiis/KNU-Project1#17]
참고링크:
 - https://kangwoo.kr/2020/03/21/kubeflow-katib-%ED%95%98%EC%9D%B4%ED%8D%BC-%ED%8C%8C%EB%9D%BC%EB%AF%B8%ED%84%B0-%ED%8A%9C%EB%8B%9D/
- https://github.com/kubeflow/katib/tree/master/examples/v1beta1/trial-images/mxnet-mnist
- https://catalog.us-east-1.prod.workshops.aws/workshops/9c0aa9ab-90a9-44a6-abe1-8dff360ae428/ko-KR/50-eks-cluster/100-launch-cluster

에러문구:
![image](https://user-images.githubusercontent.com/86493874/204304079-769221d3-9693-4b29-b5ac-c44cbd98db05.png)

도커파일 업로드 확인
(도커파일은 ecr에 업로드하였습니다.)
![image](https://user-images.githubusercontent.com/86493874/204311405-6d459637-5554-424a-9b4f-224bc85059ff.png)

![image](https://user-images.githubusercontent.com/86493874/204304184-4d29ad31-2bee-4635-955d-d8916304ddf3.png)

Dockerfile
```
FROM tensorflow/tensorflow:2.1.0-py3

RUN mkdir -p /app
ADD melonkube.py /app/

ENTRYPOINT ["python", "/app/melonkube.py"]
```

melonkube2.yaml
```
---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: melonkube
  namespace: kubeflow-user-example-com
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - accuracy
    algorithm:
      algorithmName: grid
    parallelTrialCount: 3
    maxTrialCount: 12
    maxFailedTrialCount: 3
    parameters:
      - name: --learning_rate
        parameterType: double
        feasibleSpace:
          min: "0.01"
          max: "0.2"
          step: "0.01"
      - name: --dropout
        parameterType: double
        feasibleSpace:
          min: "0.1"
          max: "0.5"
          step: "0.05"
    trialTemplate:
      primaryContainerName: training-container
      trialParameters:
        - name: learningRate
          description: Learning rate for the training model
          reference: --learning_rate
        - name: dropout
          description: rate of dropout
          reference: --dropout
      trialSpec:
        apiVersion: batch/v1
        kind: Job
        spec:
          template:
            spec:
              containers:
                - name: training-container
                  image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/melonkube
                  command:
                    - "python3"
                    - "/app/melonkube.py"
                    - "--learning_rate==${trialParameters.learningRate}"
                    - "--dropout==${trialParameters.dropout}"
              restartPolicy: Never
```

melonkube.py
```
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
import numpy as np
import argparse
from datetime import datetime, timezone

def train():
    print("TensorFlow version: ", tf.__version__)

    parser = argparse.ArgumentParser()
    parser.add_argument('--learning_rate', default=0.01, type=float)
    parser.add_argument('--dropout', default=0.2, type=float)
    args = parser.parse_args()

    mnist = tf.keras.datasets.mnist

    (x_train, y_train), (x_test, y_test) = mnist.load_data()
    x_train, x_test = x_train / 255.0, x_test / 255.0

    # Reserve 10,000 samples for validation
    x_val = x_train[-10000:]
    y_val = y_train[-10000:]
    x_train = x_train[:-10000]
    y_train = y_train[:-10000]

    model = tf.keras.models.Sequential([
      tf.keras.layers.Flatten(input_shape=(28, 28)),
      tf.keras.layers.Dense(128, activation='relu'),
      tf.keras.layers.Dropout(args.dropout),
      tf.keras.layers.Dense(10, activation='softmax')
    ])

    model.compile(optimizer=tf.keras.optimizers.SGD(learning_rate=args.learning_rate),
                  loss='sparse_categorical_crossentropy',
                  metrics=['acc'])

    print("Training...")

    katib_metric_log_callback = KatibMetricLog()
    training_history = model.fit(x_train, y_train, batch_size=64, epochs=10,
                                 validation_data=(x_val, y_val),
                                 callbacks=[katib_metric_log_callback])

    print("\\ntraining_history:", training_history.history)

    # Evaluate the model on the test data using `evaluate`
    print('\\n# Evaluate on test data')
    results = model.evaluate(x_test, y_test, batch_size=128)
    print('test loss, test acc:', results)


class KatibMetricLog(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        # RFC 3339
        local_time = datetime.now(timezone.utc).astimezone().isoformat()
        print("\\nEpoch {}".format(epoch+1))
        print("{} accuracy={:.4f}".format(local_time, logs['acc']))
        print("{} loss={:.4f}".format(local_time, logs['loss']))
        print("{} Validation-accuracy={:.4f}".format(local_time, logs['val_acc']))
        print("{} Validation-loss={:.4f}".format(local_time, logs['val_loss']))


if __name__ == '__main__':
    train()
```

참고한 공식문서 grid.yaml -> 정상적으로 실행 확인
```
---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  namespace: kubeflow-user-example-com
  name: grid
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - Train-accuracy
  algorithm:
    algorithmName: grid
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: lr
      parameterType: double
      feasibleSpace:
        min: "0.001"
        max: "0.01"
        step: "0.001"
    - name: num-layers
      parameterType: int
      feasibleSpace:
        min: "2"
        max: "5"
    - name: optimizer
      parameterType: categorical
      feasibleSpace:
        list:
          - sgd
          - adam
          - ftrl
  trialTemplate:
    primaryContainerName: training-container
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: lr
      - name: numberLayers
        description: Number of training model layers
        reference: num-layers
      - name: optimizer
        description: Training model optimizer (sdg, adam or ftrl)
        reference: optimizer
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: training-container
                image: docker.io/kubeflowkatib/mxnet-mnist:latest
                command:
                  - "python3"
                  - "/opt/mxnet-mnist/mnist.py"
                  - "--batch-size=64"
                  - "--lr=${trialParameters.learningRate}"
                  - "--num-layers=${trialParameters.numberLayers}"
                  - "--optimizer=${trialParameters.optimizer}"
            restartPolicy: Never
```

**Comment by yerim10044001** [comment]
namespace를 임의로 설정하였을때 발생하는 오류:
![image](https://user-images.githubusercontent.com/86493874/204308864-a4bf41bd-85b9-4489-b173-b5a4fbc8735a.png)

namespace_create.yaml
```
apiVersion: v1
kind: Namespace
metadata:
    name: kubeflow-user-example-com
    labels:
        katib.kubeflow.org/metrics-collector-injection: enabled
```

pod가 더이상 생성되지 않습니다.
![image](https://user-images.githubusercontent.com/86493874/204309140-a8e47d51-d2cf-4c8e-bc48-def67acf6bd0.png)

![image](https://user-images.githubusercontent.com/86493874/204309330-18ba9425-fac3-4b6f-bb00-c9401a47d1c0.png)
![image](https://user-images.githubusercontent.com/86493874/204309511-ce1847f4-7032-462c-bb62-48d547facc65.png)
![image](https://user-images.githubusercontent.com/86493874/204309694-812c0dbd-fb3e-4da3-a677-d2c690c6ad6c.png)

**Comment by yerim10044001** [comment]
추가) 컨테이너 이름(랜덤으로 생성된 컨테이너 이름) 확인 후 yaml 파일에 있는
```
primaryContainerName: zealous_northcutt
        trialParameters:
            - name: --learningRate
              description: Learning rate for the training model
              reference: --learning_rate
            - name: --dropout
              description: rate of dropout
              reference: --dropout
        trialSpec:
            apiVersion: batch/v1
            kind: Job
            spec:
                template:
                    spec:
                        containers:
                            - name: zealous_northcutt
                              image: docker.io/kubeflowkatib/mxnet-mnist:latest
                              imagePullPolicy: Never
                              command:
                                  - "python3"
                                  - "/app/melonkube.py"
                                  - "--learning_rate==${trialParameters.--learningRate}"
                                  - "--dropout==${trialParameters.--dropout}"
                        restartPolicy: Never
```
primaryContainerName: zealous_northcutt
name: zealous_northcutt
값으로 바꾼 후 돌렸는데도 결과가 바뀌지 않았습니다.

![image](https://user-images.githubusercontent.com/86493874/204312424-7000df34-b2cd-476a-8523-6bcb2b217a1e.png)

**Comment by yerim10044001** [comment]
melonkube2.yaml파일이 apply되지 않는 오류는 

```
---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: melonkube
  namespace: kubeflow-user-example-com
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - accuracy
    algorithm:
      algorithmName: grid
    parallelTrialCount: 3
    maxTrialCount: 12
    maxFailedTrialCount: 3
```
에서 algorithm:
            algorithmName: grid 의 들여쓰기 문제였습니다!

![image](https://user-images.githubusercontent.com/86493874/204544176-48721849-7d39-4b63-9799-1fdd0551414a.png)
kubectl apply 는 정상적으로 실행되었습니다!!
