### ISSUE TITLE
ImportWarning: Using Python version of hypervolume module. Expect this to be slower.

### ISSUE THREAD

**Issue by yerim10044001** [seokiis/KNU-Project1#18]
[이슈17](https://github.com/seokiis/KNU-Project1/issues/17#issue-1466548085) 에서 수정된 melonkube2.yaml파일로 실습하였습니다.

melonkube2.yaml
```
---
apiVersion: kubeflow.org/v1beta1
kind: Experiment
metadata:
  name: melonkube
  namespace: kubeflow-user-example-com
spec:
  objective:
    type: maximize
    goal: 0.99
    objectiveMetricName: Validation-accuracy
    additionalMetricNames:
      - accuracy
  algorithm:
    algorithmName: grid
  parallelTrialCount: 3
  maxTrialCount: 12
  maxFailedTrialCount: 3
  parameters:
    - name: --learning_rate
      parameterType: double
      feasibleSpace:
        min: "0.01"
        max: "0.2"
        step: "0.01"
    - name: --dropout
      parameterType: double
      feasibleSpace:
        min: "0.1"
        max: "0.5"
        step: "0.05"
  trialTemplate:
    primaryContainerName: zealous_northcutt
    trialParameters:
      - name: learningRate
        description: Learning rate for the training model
        reference: --learning_rate
      - name: dropout
        description: rate of dropout
        reference: --dropout
    trialSpec:
      apiVersion: batch/v1
      kind: Job
      spec:
        template:
          spec:
            containers:
              - name: zealous_northcutt
                image: $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/melonkube
                command:
                  - "python3"
                  - "/app/melonkube.py"
                  - "--learning_rate==${trialParameters.learningRate}"
                  - "--dropout==${trialParameters.dropout}"
            restartPolicy: Never

```

생성된 pod 확인
![image](https://user-images.githubusercontent.com/86493874/204545200-6487ac29-3852-4c10-bb7d-da0143ba2f63.png)

pod의 log 확인
![image](https://user-images.githubusercontent.com/86493874/204545294-524d6afd-95d6-4069-9a80-9b222ff0ab34.png)
![image](https://user-images.githubusercontent.com/86493874/204545323-2772949d-ac90-4f88-be6a-c69ef55a86c6.png)

아래는 정상적으로 돌아가는 random.yaml파일의 pod log입니다.
![image](https://user-images.githubusercontent.com/86493874/204545395-4ac299d5-5809-4822-ad33-9982c6431053.png)
